name: Publish Package to Crates.io

on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo fetch
      - run: cargo build
      - run: cargo test

  check:
    name: Publish check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo fetch
      - run: cargo publish --dry-run
      - run: cargo doc --no-deps

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [test, check]
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo fetch
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
